language: python
python:
  - "3.6.2"

install:
  - sudo apt-get update
  - sudo apt-get install libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev freeglut3 freeglut3-dev libnotify-dev
  - python -V
  - pip install -r requirements.txt
  
script:
  - python -m unittest discover -s tests
