language: python
python:
  - "3.6.2"

install:
  - sudo apt-get install -y dpkg-dev build-essential python-dev libjpeg-dev libtiff5-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev
  - sudo pip install -r requirements.txt
  
script:
  - python -m unittest discover -s tests
